name: blog-api
definition: src
generators:
  - name: fern-java
    version: latest
    generate:
      enabled: true
      output: ./generated-java
    config:
      packagePrefix: com.blog
      mode: client_and_server
      serverFrameworks:
        - spring
        - jersey
